spring:
  application:
    name: wanted-pre-on-boarding
  profiles:
    active: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: 'true'
  jwt:
    headers: ${JWT_HEADER}
    secret: ${JWT_SECRET_KEY}
    token-validity-in-seconds: 8640 # 1일

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace